### ISSUE TITLE
Error when options.scale_error = False

### ISSUE THREAD

**Issue by bogovicj** [TuragaLab/PyGreentea#2]
```
File "/groups/saalfeld/home/bogovicj/unet-tut/caffe-janelia/PyGreentea/PyGreentea.py", line 562, in train
    print("[Iter %i] Loss: %f, frac_pos=%f, w_pos=%f" % (i,loss,frac_pos,w_pos))
UnboundLocalError: local variable 'frac_pos' referenced before assignment
```

`frac_pos` needs a value too, or maybe better, shouldn't be printed when `scale_error` is false.

**Comment by grisaitis** [comment]
How are you providing training data to `train()`? Are they in-memory numpy arrays?

Thanks for mentioning this. I need to clean up the if-statements in that function... variables are getting initialized and referenced inconsistently. (My bad!)

**Comment by grisaitis** [comment]
This is related to https://github.com/TuragaLab/PyGreentea/issues/1 ... i think they're both caused by the if-statement soup in `train()`.

**Comment by bogovicj** [comment]
Is it?
I "fixed" (?) it by replacing:
https://github.com/TuragaLab/PyGreentea/blob/e2c5b0938ecb00e91c6f3f75b68059d73262f3ad/PyGreentea.py#L571
with 

```
 if (options.loss_function == 'euclid' or options.loss_function == 'euclid_aniso') and options.scale_error:
```

**Comment by grisaitis** [comment]
i think so. the variable `frac_pos` is being declared and then referenced in separate if-statements, and the logic there isn't lining up. same for that other issue, with `mask_slice`. the statement that declares the variable doesn't necessary execute in situations when it's being referenced.
